// JOGOS PRÉ-CADASTRADOS — Copa 2026
// Extraídos da imagem fornecida
const JOGOS_COPA2026 = [
  { data: "2026-06-11", timeA: "México",           timeB: "África do Sul",    rodada: "Fase de Grupos" },
  { data: "2026-06-11", timeA: "Coreia do Sul",    timeB: "República Tcheca", rodada: "Fase de Grupos" },
  { data: "2026-06-12", timeA: "Canadá",           timeB: "Bósnia",           rodada: "Fase de Grupos" },
  { data: "2026-06-12", timeA: "Estados Unidos",   timeB: "Paraguai",         rodada: "Fase de Grupos" },
  { data: "2026-06-13", timeA: "Catar",            timeB: "Suíça",            rodada: "Fase de Grupos" },
  { data: "2026-06-13", timeA: "Brasil",           timeB: "Marrocos",         rodada: "Fase de Grupos" },
  { data: "2026-06-14", timeA: "Alemanha",         timeB: "Curaçao",          rodada: "Fase de Grupos" },
  { data: "2026-06-14", timeA: "Holanda",          timeB: "Japão",            rodada: "Fase de Grupos" },
  { data: "2026-06-14", timeA: "Costa do Marfim",  timeB: "Equador",          rodada: "Fase de Grupos" },
  { data: "2026-06-15", timeA: "Espanha",          timeB: "Cabo Verde",       rodada: "Fase de Grupos" },
  { data: "2026-06-15", timeA: "Bélgica",          timeB: "Egito",            rodada: "Fase de Grupos" },
  { data: "2026-06-15", timeA: "Arábia Saudita",   timeB: "Uruguai",          rodada: "Fase de Grupos" },
  { data: "2026-06-16", timeA: "França",           timeB: "Senegal",          rodada: "Fase de Grupos" },
  { data: "2026-06-16", timeA: "Argentina",        timeB: "Argélia",          rodada: "Fase de Grupos" },
  { data: "2026-06-17", timeA: "Portugal",         timeB: "RD Congo",         rodada: "Fase de Grupos" },
  { data: "2026-06-17", timeA: "Inglaterra",       timeB: "Croácia",          rodada: "Fase de Grupos" },
  { data: "2026-06-18", timeA: "Suíça",            timeB: "Bósnia",           rodada: "Fase de Grupos" },
  { data: "2026-06-18", timeA: "México",           timeB: "Coreia do Sul",    rodada: "Fase de Grupos" },
  { data: "2026-06-19", timeA: "Escócia",          timeB: "Marrocos",         rodada: "Fase de Grupos" },
  { data: "2026-06-19", timeA: "Brasil",           timeB: "Haiti",            rodada: "Fase de Grupos" },
  { data: "2026-06-20", timeA: "Holanda",          timeB: "Suécia",           rodada: "Fase de Grupos" },
  { data: "2026-06-20", timeA: "Alemanha",         timeB: "Costa do Marfim",  rodada: "Fase de Grupos" },
  { data: "2026-06-21", timeA: "Tunísia",          timeB: "Japão",            rodada: "Fase de Grupos" },
  { data: "2026-06-21", timeA: "Espanha",          timeB: "Arábia Saudita",   rodada: "Fase de Grupos" },
  { data: "2026-06-22", timeA: "Argentina",        timeB: "Áustria",          rodada: "Fase de Grupos" },
  { data: "2026-06-22", timeA: "França",           timeB: "Iraque",           rodada: "Fase de Grupos" },
  { data: "2026-06-22", timeA: "Noruega",          timeB: "Senegal",          rodada: "Fase de Grupos" },
  { data: "2026-06-23", timeA: "Portugal",         timeB: "Uzbequistão",      rodada: "Fase de Grupos" },
  { data: "2026-06-23", timeA: "Inglaterra",       timeB: "Gana",             rodada: "Fase de Grupos" },
  { data: "2026-06-23", timeA: "Colômbia",         timeB: "RD Congo",         rodada: "Fase de Grupos" },
  { data: "2026-06-24", timeA: "Escócia",          timeB: "Brasil",           rodada: "Fase de Grupos" },
  { data: "2026-06-24", timeA: "República Tcheca", timeB: "México",           rodada: "Fase de Grupos" },
  { data: "2026-06-25", timeA: "Equador",          timeB: "Alemanha",         rodada: "Fase de Grupos" },
  { data: "2026-06-25", timeA: "Japão",            timeB: "Suécia",           rodada: "Fase de Grupos" },
  { data: "2026-06-25", timeA: "Turquia",          timeB: "Estados Unidos",   rodada: "Fase de Grupos" },
  { data: "2026-06-26", timeA: "Noruega",          timeB: "França",           rodada: "Fase de Grupos" },
  { data: "2026-06-26", timeA: "Uruguai",          timeB: "Espanha",          rodada: "Fase de Grupos" },
  { data: "2026-06-26", timeA: "Cabo Verde",       timeB: "Arábia Saudita",   rodada: "Fase de Grupos" },
  { data: "2026-06-27", timeA: "Croácia",          timeB: "Gana",             rodada: "Fase de Grupos" },
  { data: "2026-06-27", timeA: "Colômbia",         timeB: "Portugal",         rodada: "Fase de Grupos" },
];
